version: '3'
services:
  mkdocs:
    privileged: true
    container_name: pandoc
    image: chgray123/chgray_repro:pandoc
    entrypoint: /bin/bash -c "cd /data/tools; ls; ./PreCheckinUpdate.sh"
    #entrypoint: /bin/bash -c "cd /data/tools; ls; bash"

    volumes:
      - container_cache:/var/lib/containers:rw
      - dev_dir:/root:rw
      - c:\DevDir:/devdir_ro:ro
      - c:\Source\CDocs:/Source/CDocs:rw

      #- ./source_cache:/Source:rw


      - ../..:/data:rw
      - /data/docs/orig_media
      - ../../docs/orig_media:/data/docs/orig_media:rw

      - /data/docs/bound_docs
      - ../../bound:/data/bound:rw
      - ../../bound_docs:/data/docs/bound_docs:rw


    stdin_open: true
    tty: true

volumes:
  container_cache:
    external: false
    name: container_cache

  dev_dir:
      external: false
      name: dev_dir
