version: '3'
services:
  mkdocs:
    #privileged: true
    image: dynamictelemetry/dynamictelemetry:pandoc
    entrypoint: /bin/bash -c "cd /data/tools; ls; ./PreCheckinUpdate.sh"
    volumes:
      - ./container_cache:/var/lib/containers:rm
      - ../..:/data:ro
      - ../../docs/orig_media:/out/orig_media:ro
      - ../..:/data_rw:rw
      - ../../bound:/out/bound:rw
    stdin_open: true
    tty: true
