version: '3'
services:
  mkdocs:
    privileged: true
    container_name: bind
    image: dynamictelemetry/dynamictelemetry:pandoc
    #entrypoint: /bin/bash -c "cd /data/tools; ls; ./PreCheckinUpdate.sh"
    entrypoint: /bin/bash -c "cd /data/tools; ls; bash"

    volumes:
      - ./build_cache/containers:/var/lib/containers:rw
      - ./build_cache/CDocs:/Source/CDocs:rw
      - ../..:/data:ro
      - ../../docs/orig_media:/out/orig_media:ro
      - ../..:/data_rw:rw
      - ../../bound:/out/bound:rw
    stdin_open: true
    tty: true
