version: '3'
services:
  mkdocs:
    image: dynamictelemetry/dynamictelemetry:pandoc
    entrypoint: /bin/bash -c "cd /data/tools; ls; ./PreCheckinUpdate.sh"
    volumes:
      - ../../:/data
    stdin_open: true
    tty: true
