# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# and https://github.com/DavidAnson/markdownlint/blob/main/README.md


# look at 'mdformat' for 80 columns
# https://github.com/hukkin/mdformat

# Default state for all rules
default: true

ul-style: false
line-length: 80
no-duplicate-header:
  siblings_only: true
#ol-prefix:
#  style: ordered
no-inline-html: false
fenced-code-language: false

#
# BUGBUG : adding these suppressions, just to work around mutual exclusion in
#          pandoc.   The intent is to add them back as solutions are found.
#
list-marker-space: false
no-alt-text: false
