# Called by ci.yml to perform general linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: All linting, sanity checks

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-okay:
    needs: run-markdownlint
    needs: run-misspell
    needs: run-sanitycheck

    runs-on: ubuntu-22.04

    steps:
    - name: Passed
      run: ls
