# Called by ci.yml to perform markdown linting
# See: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
name: Lint - Markdownlint

on:
  pull_request:
    branches: [ main ]

jobs:
  run-markdownlint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: check out code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        persist-credentials: false

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
      with:
        globs: |
          **/*.md
          !SECURITY.md
          !docs/orig_media/GeneratedFileStatus.md
          !.github/**/*.md
