name: Publish GitHub Pages

on:
  pull_request:
    branches: [ main ]

jobs:
  build_mkdocs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - run: pip install \
          mkdocs \
          mkdocs-mermaid2-plugin \
          mkdocs-material \
          mkdocs-minify-plugin \
          mkdocs-include-markdown-plugin \
          mkdocs-macros-plugin \
          mkdocs-video mkdocs-redirects

    - name: Attempt strict compilation of docs
      run: mkdocs build -s

    - name: Publish
      run: mkdocs gh-deploy -s
